### ISSUE TITLE
Any action called results in "Failed to call service climate/<service>. "light"

### ISSUE THREAD

**Issue by Goose1451** [bodyscape/cielo_home#1]
Here is the info from the logger.  This was from trying to change the mode to "off".  But it's similar for every action performed.

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/cielo_home/cielohomedevice.py:345
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 1:36:09 PM (1 occurrences)
Last logged: 1:36:09 PM

[548299430048] 'light'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 968, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 720, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 497, in async_set_hvac_mode
    await self.hass.async_add_executor_job(self.set_hvac_mode, hvac_mode)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/cielo_home/climate.py", line 67, in set_hvac_mode
    self._device.send_hvac_mode(hvac_mode)
  File "/config/custom_components/cielo_home/cielohomedevice.py", line 551, in send_hvac_mode
    self.send_power_off()
  File "/config/custom_components/cielo_home/cielohomedevice.py", line 50, in send_power_off
    self._send_power("off")
  File "/config/custom_components/cielo_home/cielohomedevice.py", line 57, in _send_power
    action = self._get_action()
  File "/config/custom_components/cielo_home/cielohomedevice.py", line 345, in _get_action
    if self._device["latestAction"]["light"] == "on/off"
KeyError: 'light'

**Comment by bodyscape** [comment]
@Goose1451 I'm pretty sur i fix it. Try the version 1.3.1! ;)
