### ISSUE TITLE
myRuleConfiguration error when ever try to change a setting

### ISSUE THREAD

**Issue by nybdog** [bodyscape/cielo_home#27]
I uninstalled the old version, rebooted, installed 1.6.1, rebooted and followed the direction for getting the tokens, etc.  and closed chrome.  The login seems to be working fine, history shows the humidity, temp and connected have been solid since I updated (yesterday).  However, whenever I try to control the AC unit (power, temp, etc.) I get a 'myRuleConfiguration' error.  I've tried controlling the AC from the integration card, services tab, etc. I even just tried reinstalling the integration and still the same issue.  Anyone else seeing this?  Everything was fine before Cielo messed things up by changing the logon.
Thanks. 

Below are some logs if it helps:  
2023-09-13 18:37:21.980 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'myRuleConfiguration'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1969, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2006, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 830, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/cielo_home/climate.py", line 144, in async_sync_ac_state
    self._device.sync_ac_state(power, temp, mode, fan_speed, swing)
  File "/config/custom_components/cielo_home/cielohomedevice.py", line 114, in sync_ac_state
    self._send_msg(action, "", "", default_action="syncState")
  File "/config/custom_components/cielo_home/cielohomedevice.py", line 164, in _send_msg
    "myRuleConfiguration": self.get_my_rule_configuration(),
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/cielo_home/cielohomedevice.py", line 418, in get_my_rule_configuration
    return self._device["myRuleConfiguration"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'myRuleConfiguration'

**Comment by bodyscape** [comment]
they don't only change the login but also some data call like 'myRuleConfiguration' was not there prior the Ceilo update.
Anyway try the new version 1.6.2 tou should be ok! :)

**Comment by nybdog** [comment]
It works now! Your amazing, thank you!
