### ISSUE TITLE
Failure to connect to service

### ISSUE THREAD

**Issue by Kennyc1012** [bodyscape/cielo_home#43]
I am seeing a lot of errors when trying to do any sort of action (turn on unit, change temp, turn off unit, etc...). Looking at the logs, I see a lot of errors when trying to connect to the service and trying to refetch the auth token. Reloading the plugin solves the issue, but eventually it will start happening again.

```
2023-12-27 09:22:56.602 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration cielo_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-27 09:22:56.603 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-27 09:23:57.820 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ states('sensor.basement_thermostat_current_temperature') | round }}°F | {{ states('sensor.basement_thermostat_current_humidity') | round }}%) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1646, in forgiving_round
    value = round(float(value), precision)
                  ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unavailable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 569, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2247, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1651, in forgiving_round
    raise_no_default("round", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1627, in raise_no_default
    raise ValueError(
ValueError: Template error: round got invalid input 'unavailable' when rendering template '{{ states('sensor.basement_thermostat_current_temperature') | round }}°F | {{ states('sensor.basement_thermostat_current_humidity') | round }}%' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 695, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 571, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: round got invalid input 'unavailable' when rendering template '{{ states('sensor.basement_thermostat_current_temperature') | round }}°F | {{ states('sensor.basement_thermostat_current_humidity') | round }}%' but no default was specified
2023-12-27 09:24:26.595 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ states('sensor.basement_thermostat_current_temperature') | round }}°F | {{ states('sensor.basement_thermostat_current_humidity') | round }}%) renders=6>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1646, in forgiving_round
    value = round(float(value), precision)
                  ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unavailable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 569, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2247, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1651, in forgiving_round
    raise_no_default("round", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1627, in raise_no_default
    raise ValueError(
ValueError: Template error: round got invalid input 'unavailable' when rendering template '{{ states('sensor.basement_thermostat_current_temperature') | round }}°F | {{ states('sensor.basement_thermostat_current_humidity') | round }}%' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 695, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 571, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: round got invalid input 'unavailable' when rendering template '{{ states('sensor.basement_thermostat_current_temperature') | round }}°F | {{ states('sensor.basement_thermostat_current_humidity') | round }}%' but no default was specified
2023-12-27 09:25:10.198 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.openweathermap_rain (mm/h) cannot be converted to the unit of previously compiled statistics (in). Generation of long term statistics will be suppressed unless the unit changes back to in or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-12-27 09:25:10.198 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.openweathermap_snow (mm/h) cannot be converted to the unit of previously compiled statistics (in). Generation of long term statistics will be suppressed unless the unit changes back to in or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-12-27 12:58:46.270 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.50 data: Unable to connect to the device: 192.168.0.50:9999: 
2023-12-27 13:48:57.522 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-27 13:54:54.684 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-27 13:57:00.676 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-27 14:00:41.261 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-27 14:07:17.888 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-27 14:11:09.554 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-27 14:15:44.188 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-27 14:39:03.453 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-27 14:40:36.482 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-27 14:48:55.293 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-27 16:21:35.269 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.50 data: Unable to connect to the device: 192.168.0.50:9999: 
2023-12-27 16:47:51.142 WARNING (Thread-9) [pychromecast.socket_client] [Living Room TV(192.168.0.90):8009] Heartbeat timeout, resetting connection
2023-12-27 16:48:21.167 ERROR (Thread-9) [pychromecast.socket_client] [Living Room TV(192.168.0.90):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.0.90', 8009)), retrying in 5.0s
2023-12-27 20:08:06.464 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-27 20:27:28.472 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-27 20:33:06.684 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-27 20:44:46.867 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 00:50:22.269 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.50 data: Unable to connect to the device: 192.168.0.50:9999: 
2023-12-28 00:56:56.268 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.50 data: Unable to connect to the device: 192.168.0.50:9999: 
2023-12-28 02:02:00.684 WARNING (Thread-8) [pychromecast.socket_client] [Bedroom speaker(192.168.0.89):8009] Heartbeat timeout, resetting connection
2023-12-28 02:02:01.715 ERROR (Thread-8) [pychromecast.socket_client] [Bedroom speaker(192.168.0.89):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.0.89', 8009)), retrying in 5.0s
2023-12-28 02:18:04.507 WARNING (Thread-5) [pychromecast.socket_client] [Home(192.168.0.71):8009] Heartbeat timeout, resetting connection
2023-12-28 02:18:19.873 ERROR (Thread-5) [pychromecast.socket_client] [Home(192.168.0.71):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.0.71', 8009)), retrying in 5.0s
2023-12-28 04:41:06.009 ERROR (Thread-7) [pychromecast.socket_client] [Living Room display(192.168.0.88):8009] Error reading from socket.
2023-12-28 04:41:06.010 WARNING (Thread-7) [pychromecast.socket_client] [Living Room display(192.168.0.88):8009] Error communicating with socket, resetting connection
2023-12-28 04:41:06.019 ERROR (Thread-7) [pychromecast.socket_client] [Living Room display(192.168.0.88):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.0.88', 8009)), retrying in 5.0s
2023-12-28 10:19:15.600 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 10:20:14.811 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 10:24:09.481 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 10:30:32.838 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 10:33:17.462 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 10:35:23.546 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 10:37:42.866 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 10:42:45.066 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 10:45:45.073 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 18:08:43.571 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 18:17:53.739 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 18:20:07.682 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 18:26:05.548 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 18:32:18.474 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 18:45:47.470 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 18:49:52.418 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 18:55:03.591 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 18:58:06.531 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 18:59:02.966 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 19:00:40.488 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 19:04:37.490 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 19:07:50.671 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 19:08:49.543 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 19:10:26.678 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-28 20:39:25.359 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.50 data: Unable to connect to the device: 192.168.0.50:9999: [Errno 113] Connect call failed ('192.168.0.50', 9999)
2023-12-28 21:46:07.471 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.50 data: Unable to connect to the device: 192.168.0.50:9999: [Errno 113] Connect call failed ('192.168.0.50', 9999)
2023-12-28 23:49:47.439 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.50 data: Unable to connect to the device: 192.168.0.50:9999: [Errno 113] Connect call failed ('192.168.0.50', 9999)
2023-12-29 02:49:02.836 WARNING (Thread-8) [pychromecast.socket_client] [Bedroom speaker(192.168.0.89):8009] Heartbeat timeout, resetting connection
2023-12-29 02:49:21.663 ERROR (Thread-8) [pychromecast.socket_client] [Bedroom speaker(192.168.0.89):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.0.89', 8009)), retrying in 5.0s
2023-12-29 03:17:44.094 ERROR (Thread-7) [pychromecast.socket_client] [Living Room display(192.168.0.88):8009] Error reading from socket.
2023-12-29 03:17:44.094 WARNING (Thread-7) [pychromecast.socket_client] [Living Room display(192.168.0.88):8009] Error communicating with socket, resetting connection
2023-12-29 03:17:44.109 ERROR (Thread-7) [pychromecast.socket_client] [Living Room display(192.168.0.88):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.0.88', 8009)), retrying in 5.0s
2023-12-29 04:27:40.366 WARNING (Thread-5) [pychromecast.socket_client] [Home(192.168.0.71):8009] Heartbeat timeout, resetting connection
2023-12-29 04:27:47.504 ERROR (Thread-5) [pychromecast.socket_client] [Home(192.168.0.71):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.0.71', 8009)), retrying in 5.0s
2023-12-29 09:50:11.485 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.samsung_q80_series_65 is taking over 10 seconds
2023-12-29 09:57:21.067 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-29 10:03:52.693 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-29 10:13:32.928 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-29 10:15:26.931 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.52 data: Unable to query the device 192.168.0.52:9999: 
2023-12-29 11:39:52.712 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [140202230056512] from fe80::1cb5:f6ca:d41d:a230 (Home Assistant/2023.12 (io.robbie.HomeAssistant; build:2023.499; iPadOS 17.1.1)): Disconnected: Did not receive auth message within 10 seconds
2023-12-29 12:22:05.207 DEBUG (MainThread) [custom_components.cielo_home.cielohome] Send Json : {"action": "actionControl", "macAddress": "REDACTED", "deviceTypeVersion": "BB02", "fwVersion": "1.0.9,2.4.0", "actionSource": "WEB", "applianceType": "AC", "applianceId": 308, "myRuleConfiguration": {}, "connection_source": 0, "user_id": "REDACTED", "token": "*****", "mid": "chrome-1696167032", "preset": 0, "application_version": "1.0.0", "ts": 1703888525, "actions": {"power": "on", "mode": "heat", "fanspeed": "auto", "temp": "74", "swing": "auto", "light": "off", "followme": "off"}, "oldPower": "on", "actionType": "temp", "actionValue": 74}
2023-12-29 12:23:38.893 DEBUG (MainThread) [custom_components.cielo_home.cielohome] Send Json : {"action": "actionControl", "macAddress": "REDACTED", "deviceTypeVersion": "BB02", "fwVersion": "1.0.9,2.4.0", "actionSource": "WEB", "applianceType": "AC", "applianceId": 308, "myRuleConfiguration": {}, "connection_source": 0, "user_id": "REDACTED", "token": "*****", "mid": "chrome-1696167032", "preset": 0, "application_version": "1.0.0", "ts": 1703888618, "actions": {"power": "on", "mode": "heat", "fanspeed": "auto", "temp": "82", "swing": "auto", "light": "off", "followme": "off"}, "oldPower": "on", "actionType": "temp", "actionValue": 82}
2023-12-29 12:24:05.417 DEBUG (MainThread) [custom_components.cielo_home.cielohome] Send Json : {"action": "actionControl", "macAddress": "E868E7DBCD55", "deviceTypeVersion": "BB02", "fwVersion": "1.0.9,2.4.0", "actionSource": "WEB", "applianceType": "AC", "applianceId": 308, "myRuleConfiguration": {}, "connection_source": 0, "user_id": "REDACTED", "token": "*****", "mid": "chrome-1696167032", "preset": 0, "REDACTED_version": "1.0.0", "ts": 1703888645, "actions": {"power": "on", "mode": "heat", "fanspeed": "auto", "temp": "80", "swing": "auto", "light": "off", "followme": "off"}, "oldPower": "on", "actionType": "temp", "actionValue": 80}
2023-12-29 12:31:27.407 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.73 data: Unable to connect to the device: 192.168.0.73:9999: 
2023-12-30 03:16:33.269 ERROR (MainThread) [homeassistant.components.tplink.coordinator] Error fetching 192.168.0.50 data: Unable to connect to the device: 192.168.0.50:9999: 
2023-12-30 03:27:24.003 ERROR (Thread-7) [pychromecast.socket_client] [Living Room display(192.168.0.88):8009] Error reading from socket.
2023-12-30 03:27:24.003 WARNING (Thread-7) [pychromecast.socket_client] [Living Room display(192.168.0.88):8009] Error communicating with socket, resetting connection
2023-12-30 03:27:24.017 ERROR (Thread-7) [pychromecast.socket_client] [Living Room display(192.168.0.88):8009] Failed to connect to service ServiceInfo(type='mdns', data='google-nest-hub-d30d677f19d251bc3dd80560ec2de57f._googlecast._tcp.local.'), retrying in 5.0s
2023-12-30 03:48:57.110 WARNING (Thread-8) [pychromecast.socket_client] [Bedroom speaker(192.168.0.89):8009] Heartbeat timeout, resetting connection
2023-12-30 03:49:16.114 ERROR (Thread-8) [pychromecast.socket_client] [Bedroom speaker(192.168.0.89):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.0.89', 8009)), retrying in 5.0s
2023-12-30 04:22:25.694 WARNING (Thread-5) [pychromecast.socket_client] [Home(192.168.0.71):8009] Heartbeat timeout, resetting connection
2023-12-30 04:22:41.213 ERROR (Thread-5) [pychromecast.socket_client] [Home(192.168.0.71):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.0.71', 8009)), retrying in 5.0s
2023-12-30 08:03:18.242 DEBUG (MainThread) [custom_components.cielo_home.cielohome] Send Json : {"action": "actionControl", "macAddress": "REDACTED", "deviceTypeVersion": "BB02", "fwVersion": "1.0.9,2.4.0", "actionSource": "WEB", "applianceType": "AC", "applianceId": 308, "myRuleConfiguration": {}, "connection_source": 0, "user_id": "REDACTED", "token": "*****", "mid": "chrome-1696167032", "preset": 0, "application_version": "1.0.0", "ts": 1703959398, "actions": {"power": "on", "mode": "heat", "fanspeed": "auto", "temp": "74", "swing": "auto", "light": "off", "followme": "off"}, "oldPower": "on", "actionType": "temp", "actionValue": 74}
2023-12-30 08:03:20.452 DEBUG (MainThread) [custom_components.cielo_home.cielohome] Send Json : {"action": "actionControl", "macAddress": "REDACTED", "deviceTypeVersion": "BB02", "fwVersion": "1.0.9,2.4.0", "actionSource": "WEB", "applianceType": "AC", "applianceId": 308, "myRuleConfiguration": {}, "connection_source": 0, "user_id": "REDACTED", "token": "*****", "mid": "chrome-1696167032", "preset": 0, "application_version": "1.0.0", "ts": 1703959400, "actions": {"power": "off", "mode": "heat", "fanspeed": "auto", "temp": "74", "swing": "auto", "light": "off", "followme": "off"}, "oldPower": "on", "actionType": "power", "actionValue": "off"}
2023-12-30 08:03:23.672 DEBUG (MainThread) [custom_components.cielo_home.cielohome] Send Json : {"action": "actionControl", "macAddress": "REDACTED", "deviceTypeVersion": "BB02", "fwVersion": "1.0.9,2.4.0", "actionSource": "WEB", "applianceType": "AC", "applianceId": 308, "myRuleConfiguration": {}, "connection_source": 0, "user_id": "REDACTED", "token": "*****", "mid": "chrome-1696167032", "preset": 0, "application_version": "1.0.0", "ts": 1703959403, "actions": {"power": "on", "mode": "heat", "fanspeed": "auto", "temp": "74", "swing": "auto", "light": "off", "followme": "off"}, "oldPower": "on", "actionType": "power", "actionValue": "on"}
2023-12-30 08:03:27.892 DEBUG (MainThread) [custom_components.cielo_home.cielohome] Send Json : {"action": "actionControl", "macAddress": "REDACTED", "deviceTypeVersion": "BB02", "fwVersion": "1.0.9,2.4.0", "actionSource": "WEB", "applianceType": "AC", "applianceId": 308, "myRuleConfiguration": {}, "connection_source": 0, "user_id": "REDACTED", "token": "*****", "mid": "chrome-1696167032", "preset": 0, "application_version": "1.0.0", "ts": 1703959407, "actions": {"power": "on", "mode": "heat", "fanspeed": "auto", "temp": "72", "swing": "auto", "light": "off", "followme": "off"}, "oldPower": "on", "actionType": "temp", "actionValue": 72}
```

**Comment by Kennyc1012** [comment]
AFter looking at the logs closer, errors are not from this plugin.
